import React from "react";
import styles from "./page.module.css";
import Image from "next/image";
import Button from "@/components/Button/button";




export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <div className={styles.container}>
      <div className={styles.imgContainer}>
        <Image src="/aboutContainer.png" alt="" fill={true} className={styles.img} />
        <div className={styles.imgText}>
          <h2>Digital StoryTellers</h2>
          <h3>Handcrafting award winning digital experiences</h3>
        </div>
      </div>
      <div className={styles.textContainer}>
        <div className={styles.item}>
          <h1>Who are you?</h1>
          <p>
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            facilisi. Sed nec nisl eu orci eleifend ullamcorper. Vivamus luctus
            augue eget ligula tincidunt, sit amet fermentum quam venenatis."
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
          </p>
        </div>
        <div className={styles.item}>
          <h1>What we do?</h1>
          <p>
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
            facilisi. Sed nec nisl eu orci eleifend ullamcorper. Vivamus luctus
            augue eget ligula tincidunt, sit amet fermentum quam venenatis."
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
          </p>
          <Button url="/contact" text="Contact"/>
        </div>
      </div>
    </div>
  );
};

export default About;
