import React from 'react'
import styles from "./page.module.css"
import Link from 'next/link'


export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

const Portfolio = () => {
  return (
    <div className={styles.container}>
      <h1>Choose a Gallery</h1>
      <div className={styles.items}>
        <Link href="/portfolio/illustrations" className={styles.item}>
          <span className={styles.spans}>illustrations</span>
        </Link>
        <Link href="/portfolio/websites" className={styles.item}>
          <span className={styles.spans}>Web Sites</span>
        </Link>
        <Link href="/portfolio/applications" className={styles.item}>
          <span className={styles.spans}>Application</span>
        </Link>
      </div>
    </div>
  )
}

export default Portfolio